architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    mixin { useLegacyMixinAp = true }
}

apply from: rootProject.file("gradle/scripts/platform.gradle")

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    implementation project(path: ":fabric", configuration: "namedElements")
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    common(project(path: ":testmod-common", configuration: "namedElements")) { transitive false }

    modImplementation "com.daqem.uilib:uilib-fabric:${project.uilib_version}"
    modImplementation "org.snakeyaml:snakeyaml-engine:${project.yaml_version}"
    modImplementation "com.electronwill.night-config:toml:${project.toml_version}"
    modImplementation "com.electronwill.night-config:core:${project.toml_version}"
    modImplementation "blue.endless:jankson:${project.json5_version}"
    modImplementation("org.spongepowered:configurate-hocon:${project.hocon_version}") {
        exclude group: 'org.checkerframework'
    }
}