plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation "com.daqem.uilib:uilib-fabric:${project.uilib_version}"
    modImplementation "org.snakeyaml:snakeyaml-engine:${project.yaml_version}"
    modImplementation "com.electronwill.night-config:toml:${project.toml_version}"
    modImplementation "com.electronwill.night-config:core:${project.toml_version}"
    modImplementation "blue.endless:jankson:${project.json5_version}"
    modImplementation("org.spongepowered:configurate-hocon:${project.hocon_version}") {
        exclude group: 'org.checkerframework'
    }

    shadowBundle "org.snakeyaml:snakeyaml-engine:${project.yaml_version}"
    shadowBundle "com.electronwill.night-config:toml:${project.toml_version}"
    shadowBundle "com.electronwill.night-config:core:${project.toml_version}"
    shadowBundle "blue.endless:jankson:${project.json5_version}"
    shadowBundle("org.spongepowered:configurate-hocon:${project.hocon_version}") {
        exclude group: 'org.checkerframework'
    }
}

apply from: rootProject.file("gradle/scripts/publishing.gradle")
apply from: rootProject.file("gradle/scripts/maven-publishing.gradle")

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}