architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

apply from: rootProject.file("gradle/scripts/platform.gradle")
apply from: rootProject.file("gradle/scripts/publishing.gradle")
apply from: rootProject.file("gradle/scripts/maven-publishing.gradle")

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')

    modImplementation "com.daqem.uilib:uilib-fabric:${project.uilib_version}"
    modImplementation "org.snakeyaml:snakeyaml-engine:${project.yaml_version}"
    modImplementation "com.electronwill.night-config:toml:${project.toml_version}"
    modImplementation "com.electronwill.night-config:core:${project.toml_version}"
    modImplementation "blue.endless:jankson:${project.json5_version}"
    modImplementation("org.spongepowered:configurate-hocon:${project.hocon_version}") {
        exclude group: 'org.checkerframework'
    }

    shadowBundle "org.snakeyaml:snakeyaml-engine:${project.yaml_version}"
    shadowBundle "com.electronwill.night-config:toml:${project.toml_version}"
    shadowBundle "com.electronwill.night-config:core:${project.toml_version}"
    shadowBundle "blue.endless:jankson:${project.json5_version}"
    shadowBundle("org.spongepowered:configurate-hocon:${project.hocon_version}") {
        exclude group: 'org.checkerframework'
    }
}