plugins {
    id 'multiloader-common'
    id 'com.gradleup.shadow'
}

configurations {
    commonJava{
        canBeResolved = true
    }
    commonResources{
        canBeResolved = true
    }

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id-common"
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

shadowJar {
    configurations = [project.configurations.shadowBundle]

    // YAML
    relocate "org.snakeyaml", "com.daqem.yamlconfig.libs.snakeyaml"

    // TOML
    relocate "com.electronwill.nightconfig", "com.daqem.yamlconfig.libs.nightconfig"

    // JSON5
    relocate "blue.endless.jankson", "com.daqem.yamlconfig.libs.jankson"

    // HOCON
    relocate "org.spongepowered.configurate", "com.daqem.yamlconfig.libs.configurate"
    relocate "com.typesafe.config", "com.daqem.yamlconfig.libs.typesafe.config"
    relocate "io.leangen.geantyref", "com.daqem.yamlconfig.libs.geantyref"

    archiveClassifier = ""

    mergeServiceFiles()
}

assemble.dependsOn shadowJar