org.gradle.jvmargs=-Xmx4096M

enabled_platforms=fabric,neoforge
maven_group=com.daqem
archives_base_name=yamlconfig

# Project
mod_version=1.1-1.21.5
mod_id=yamlconfig
mod_name=YAML Config
mod_description=A Minecraft configuration mod based on the YAML file format.
mod_author=DAQEM
mod_license=Apache-2.0
mod_website=https://daqem.com
mod_repository=https://github.com/DAQEM/YAMLConfig

# Publishing
supported_minecraft_versions=1.21.5
release_type=release

curse_forge_project_id=1128669
curseforge_dependencies=architectury-api,ui

modrinth_project_id=L1FFB418
modrinth_dependencies=architectury-api,ui-lib

# Minecraft
minecraft_version=1.21.5

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.119.5+1.21.5

# Forge
forge_version=51.0.13
forge_loader_version=51

# NeoForge
neoforge_version=21.5.2-beta
neoforge_loader_version=7

# Dependencies
architectury_version=16.0.3

ui_library_version=1.0-1.21.5
ui_library_file_fabric=6352522
ui_library_file_fabric_sources=6352523
ui_library_file_neoforge=6352524