plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    mods {
        forge {
            sourceSet project(":neoforge").sourceSets.main
        }
    }
}

architectury {
    platformSetupLoomIde()
    neoForge {
        platformPackage = "neoforge"
    }
}

configurations {
    common
    forgeLike
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"

    implementation(project(path: ":neoforge", configuration: "namedElements")) { transitive false }
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    common(project(path: ":testmod-common", configuration: "namedElements")) { transitive false }

    modImplementation "com.daqem.uilib:uilib-neoforge:${project.ui_library_version}"

    modImplementation "org.snakeyaml:snakeyaml-engine:2.7"
    modImplementation "com.electronwill.night-config:toml:3.6.6"
    modImplementation "com.electronwill.night-config:core:3.6.6"
    modImplementation "blue.endless:jankson:1.2.3"
    modImplementation("org.spongepowered:configurate-hocon:4.1.2") {
        exclude group: 'org.checkerframework'
    }
}
