architectury {
    platformSetupLoomIde()
    neoForge {
        platformPackage = "neoforge"
    }
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    mods {
        forge {
            sourceSet project(":neoforge").sourceSets.main
        }
    }
}

configurations {
    forgeLike
    common
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

apply from: rootProject.file("gradle/scripts/platform.gradle")

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    implementation(project(path: ":neoforge", configuration: "namedElements")) { transitive false }
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    common(project(path: ":testmod-common", configuration: "namedElements")) { transitive false }

    modImplementation "com.daqem.uilib:uilib-neoforge:${project.uilib_version}"
    modImplementation "org.snakeyaml:snakeyaml-engine:${project.yaml_version}"
    modImplementation "com.electronwill.night-config:toml:${project.toml_version}"
    modImplementation "com.electronwill.night-config:core:${project.toml_version}"
    modImplementation "blue.endless:jankson:${project.json5_version}"
    modImplementation("org.spongepowered:configurate-hocon:${project.hocon_version}") {
        exclude group: 'org.checkerframework'
    }
}