architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/${rootProject.mod_id}.accesswidener")
}

apply from: rootProject.file("gradle/scripts/maven-publishing.gradle")

dependencies {
    // Fabric loader for annotations/mixins (Architectury standard)
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "com.daqem.uilib:uilib-common:${project.uilib_version}"
    modImplementation "org.snakeyaml:snakeyaml-engine:${project.yaml_version}"
    modImplementation "com.electronwill.night-config:toml:${project.toml_version}"
    modImplementation "com.electronwill.night-config:core:${project.toml_version}"
    modImplementation "blue.endless:jankson:${project.json5_version}"
    modImplementation("org.spongepowered:configurate-hocon:${project.hocon_version}") {
        exclude group: 'org.checkerframework'
    }
}