modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
issueTrackerURL = "${mod_repository}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
license = "${mod_license}"
displayName = "${mod_name}"
authors = "${mod_author}"
credits = "SnakeYAML, NightConfig, Jankson, Configurate, Geantyref, TypeSafe Config"
description = """
${mod_description}

Includes libraries: SnakeYAML (Apache 2.0), NightConfig (LGPL 3.0), Jankson (MIT), Configurate (Apache 2.0), Geantyref (Apache 2.0) and TypeSafe Config (Apache 2.0).
"""

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "uilib"
type = "required"
versionRange = "[${ui_library_version},)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "yamlconfig-common.mixins.json"