modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
issueTrackerURL = "${mod_repository}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
license = "${mod_license}"
displayName = "${mod_name}"
authors = "${mod_author}"
credits = "${mod_author}"
description = "${mod_description}"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "uilib"
type = "required"
versionRange = "[${ui_library_version},)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "yamlconfig-common.mixins.json"