modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mods]]
modId = "yamlconfig_test"
version = "1.0.0"
displayName = "YAML Condig Test Mod"
authors = "DAQEM"
description = '''
This is a test mod for YAML Config.
'''
license = "Apache-2.0"